version: '3'

services:
  shock:
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    restart: always
    working_dir: /opt/shock
    volumes:
      - ./:/opt/shock